; Configuración de archivos y memoria
file_uploads = On
memory_limit = 512M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 300
max_input_time = 300

; SEGURIDAD DE PRODUCCIÓN
; Ocultar la versión de PHP en las cabeceras HTTP (X-Powered-By)
expose_php = Off

; Desactivar errores en pantalla (para que un intruso no vea rutas completas o consultas fallidas)
display_errors = Off
display_startup_errors = Off
log_errors = On

; DESACTIVAR FUNCIONES PELIGROSAS DE LA CONSOLA LINUX
disable_functions = exec,passthru,shell_exec,system,proc_open,popen,curl_multi_exec,parse_ini_file,show_source