name: Despliegue Automático al VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar en el servidor
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Ejecutar despliegue en VPS por SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # 1. Entrar a la ruta del proyecto
            cd /var/www/svpmph

            # 2. Descargar los cambios
            git pull origin main

            # 3. Levantar contenedores con Docker
            docker compose -f docker-compose.yml up -d --build
